### ISSUE TITLE
ERROR - Failed to Query Poloniex for Balance Data, Restarting Loop

### ISSUE THREAD

**Issue by fachos** [BatuhanUsluel/ArbitrageBot#11]
may i know what the problem?

**Comment by BatuhanUsluel** [comment]
Sorry for not getting back earlier,

Did you enter your api keys&secret into the arbbot.conf file before running? Because if you didn't, you will get this message. Also you may want to recreate your api key, as with poloniex there are occasionally problems with api keys that have been created a while back.
